# Site settings
title: Danica Yong
email: your-email@domain.com
url: https://dannikaaa.github.io
description: "Data Science | Marketing Analytics | Machine Learning"
#It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Danica Yong

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: kaggle
    url: https://www.kaggle.com/skyartemis
  - title: github
    url: http://github.com/dannikaaa/

# Build settings
markdown: kramdown
permalink: pretty
